# golangci-lint configuration

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - noctx
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: package-comments
        disabled: false
      - name: var-naming
        disabled: true

  gosec:
    excludes:
      - G104
      - G204

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: pkg/types/
      linters:
        - revive
      text: "var-naming: avoid meaningless package names"