version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - noctx
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104
        - G204
    misspell:
      locale: US
    revive:
      rules:
        - name: package-comments
          disabled: false
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - revive
        path: pkg/types/
        text: 'var-naming: avoid meaningless package names'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
